### ISSUE TITLE
Implement functionality to switch between left-hand drive and right-hand drive

### ISSUE THREAD

**Issue by i315315** [amosproj/amos2022ws02-automotive-test-app#109]
## User story
1. As a user
2. I want to be able to switch between left-hand drive and right-hand drive in the vehicle properties context area
3. So that I can simulate how an app changes according to the driver seat position.

The default should be left-hand drive. When clicking the button, it should change to right-hand drive.
When the button is switched to right-hand drive, e.g., the apps should change their layout and the microphone used for calls changes to the microphone on the right-hand side of the car.
When the button is switched back to left-hand drive, all settings should be reversed back to the left-hand side view.

## Notes
This might help: https://developer.android.com/reference/android/car/VehicleAreaWheel

## Acceptance criteria
* In the vehicle properties context area, there is a toggle button to switch between left-hand drive and right-hand drive.
* Default is left-hand drive.
* When I toggle the button to right-hand drive, the car switches its screens to the right-hand drive view and other settings, e.g., microphone selection is changed.
* When I toggle the button again, it switches back to left-hand drive.

## Definition of done (DoD)
* Code compiles and builds 
* Acceptance criteria are met
* Tests have been written and were passed 
* Code is peer-reviewed 
* Feature is merged into development branch
* Documentation is updated 
* Bill of Materials is updated

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by LaraSlzb** [comment]
The property INFO_DRIVER_SEAT is an attribute in the car hardware. Our app has only reading permission for it (#VEHICLE_PROPERTY_ACCESS_READ) and cannot change it (#VEHICLE_PROPERTY_CHANGE_MODE_STATIC).(https://android.googlesource.com/platform/packages/services/Car/+/master/car-lib/src/android/car/VehiclePropertyIds.java).
So it is not possible to implement this functionality.
