### ISSUE TITLE
Implement functionality to switch between day and night mode in the system

### ISSUE THREAD

**Issue by i315315** [amosproj/amos2022ws02-automotive-test-app#111]
## User story
1. As a User
2. I want to be able to switch between day & night mode in the whole system
3. So that I have the possibility to choose between a dark or light color scheme 

With this User story the functionality of switching between day mode and night mode in the whole system is to be done. 
The switch between day and night mode in our app has already been implemented with #51 .
The day mode/night mode should stay activated, until it’s actively deactivated.
If the day mode/night mode is activated, it should be activated for the whole system, also when switching between apps.

The current tile "Dark Mode" should be updated so that it changes icons and names when the functionality is changed, i.e., when the night mode is activated, it has a moon, when day mode is activated, it has a sun.

## Acceptance criteria
* The functionality of changing the whole system to day mode/night mode is implemented.
* The day mode/night mode stays activated until it is deactivated.
* If day mode/night mode is activated, it should apply to the whole system.

## Notes
Note from industry partner:

Try out Vehicle Property "NightMode": https://developer.android.com/reference/android/car/VehiclePropertyIds#NIGHT_MODE 
Also possibly helpful: https://stackoverflow.com/questions/65503465/how-to-get-car-vin-info-using-car-api

Internally they have implemented it via an ADB Command: 
`Switch on nightMode with ADB: dumpsys car_service inject-vhal-event 0x11200407 true`
  
## Definition of done (DoD)
* Code compiles and builds 
* Acceptance criteria are met
* Tests have been written and were passed 
* Code is peer-reviewed 
* Feature is merged into development branch
* Documentation is updated 
* Bill of Materials is updated

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by i315315** [comment]
To be discussed: how do we handle the switch between day/night mode in our own app? Suggestion: implement a "App Settings" context area, where settings within the app can be changed.

**Comment by Andy3189** [comment]
Ziemlich sicher nicht möglich das Dark/Light Theme des Autos einzustellen, das kann der Nutzer nicht mal in den Einstellungen machen. Selbst wenn unsere App Systemrechte kriegt, es gibt einfach gar keine Systemeinstellung dafür in Automotive

**Comment by i315315** [comment]
It was investigated how to solve the issue, but it is not possible to implement issue due to technical constraints.
