### ISSUE TITLE
Research if functionality of changing the vehicle identifier number

### ISSUE THREAD

**Issue by stefanieschreiner** [amosproj/amos2022ws02-automotive-test-app#136]
## User story
1. As a user
2. I want to be able to edit the vehicle identifier number in the vehicle properties context
3. So that I can change the vehicle identifier number of my car.

With this user story, the functionality to change the vehicle identifier number is to be researched. If it is possible to change it, the implementation of the functionality will be done with a later user story.
The button has been implemented with user story #141 .

## Acceptance criteria
* In the vehicle properties context area, it is possible to change the vehicle identifier number.

## Definition of done (DoD)
* Code compiles and builds 
* Acceptance criteria are met
* Tests have been written and were passed 
* Code is peer-reviewed 
* Feature is merged into development branch
* Documentation is updated 
* Bill of Materials is updated

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by EmreR7** [comment]
Not editable because INFO_VIN is a final variable. the vehicle identifier number is only readable with system permissions.
https://developer.android.com/reference/android/car/VehiclePropertyIds#INFO_VIN
