### ISSUE TITLE
Implement functionality to change the battery level for the low-battery message

### ISSUE THREAD

**Issue by stefanieschreiner** [amosproj/amos2022ws02-automotive-test-app#138]
## User story
1. As a user
2. I want to be able to edit the battery level for the low-battery level in the vehicle properties context
3. So that I can test the popup of a low-battery message for different car manufacturers with different low battery level requirements.

With this user story, the implementation of the functionality to change the battery level for the low-battery message is to be implemented. The button has been designed with user story #141 .

## Acceptance criteria
* In the vehicle properties context area, it is possible to change the battery level for the low-battery level message.

## Definition of done (DoD)
* Code compiles and builds 
* Acceptance criteria are met
* Tests have been written and were passed.
* Code is peer-reviewed 
* Feature is merged into development branch
* Documentation is updated 
* Bill of Materials is updated

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by i315315** [comment]
Has already been implemented in with #141
