### ISSUE TITLE
Implement functionality of activating/deactivating a MediaBrowserService

### ISSUE THREAD

**Issue by i315315** [amosproj/amos2022ws02-automotive-test-app#167]
## User story
1. As a user
2. I want to be able to simulate a media source
3. So that I can test if an app to be tested handles events correctly.

With this user story, the activating/deactivating of a MediaBrowserService is to be implemented.
The toggle button to activate/deactive a MediaBrowserService has been implemented in #165 .

The MediaBrowserService should be used in order to simulate a media source. Therefore, three sample songs (Be aware of licensing!) should be stored in our app that can be played when the MediaBrowserService was chosen as the desired media source from the user.

If the MediaBrowserService is deactivated, when clicking on the toggle button, the MediaBrowserService should be activated.

As soon as the MediaBrowserService is activated, all events from the MediaBrowserService should be logged in the terminal window. Ideally, the logs get an identifier that identify them as MediaBrowserService-logs.

As soon as the MediaBrowserService is deactivated, no events should be logged anymore.

## Acceptance criteria
* In the media play area, it is possible to activate/deactive a MediaBrowserService.
* When activated, all MediaBrowserService events are logged in the terminal window.
* The list of events that should be logged is easily extendable.
* When deactivated, no events are logged anymore.

## Definition of done (DoD)
* Code compiles and builds 
* Acceptance criteria are met
* Tests have been written and were passed 
* Code is peer-reviewed 
* Feature is merged into development branch
* Documentation is updated 
* Bill of Materials is updated

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by BETuncay** [comment]
The feature should be possible to implement, however we could not find a way to make it work. The connection between the client (MainActivity, MediaBrowser/Controller/UI) with the server (MediaBrowserService/MediaSession/MediaPlayer) did not work. Even after we implemented everything according to the documentation, the MediaSession did not respond to UI events according to the defined callbacks.
