### ISSUE TITLE
Update UML in the documentation

### ISSUE THREAD

**Issue by stefanieschreiner** [amosproj/amos2022ws02-automotive-test-app#175]
## User story
1. As a user
2. I want to be able to have access to an up to date documentation
3. So that I can rely on it in case of questions 

With this user story, the UML Diagram is to be updated. 

## Acceptance criteria
* In the documentation, there is an updated version of the UML Diagram. 

## Notes
Andy already has a draft from the last one. See comment below.

## Definition of done (DoD)
* Code compiles and builds 
* Acceptance criteria are met
* Tests have been written and were passed 
* Code is peer-reviewed 
* Feature is merged into development branch
* Documentation is updated 
* Bill of Materials is updated

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by Andy3189** [comment]
[uml.drawio.zip](https://github.com/amosproj/amos2022ws02-automotive-test-app/files/10499177/uml.drawio.zip)

**Comment by EmreR7** [comment]
2nd version


[uml-5.drawio.zip](https://github.com/amosproj/amos2022ws02-automotive-test-app/files/10531027/uml-5.drawio.zip)

**Comment by EmreR7** [comment]
3rd version 

[uml-5-2.drawio.zip](https://github.com/amosproj/amos2022ws02-automotive-test-app/files/10612033/uml-5-2.drawio.zip)
