### ISSUE TITLE
Create Demo Day video

### ISSUE THREAD

**Issue by i315315** [amosproj/amos2022ws02-automotive-test-app#197]
## User story
1. As a Demo Day visitor
2. I want to be able to see a demo of the software
3. So that I can see what has been developed in the project.

With this user story, the Demo Day video for the Demo Day should be created.

The video should be a 3min. video to be shown at the demo day.
You should show at least one slide with requirements (done by POs) and one with design/architecture.
The video should include a demo of the software with corresponding spoken audio that explains the software.

## Acceptance criteria
* A Demo Day video has been created.
* The video is 3min. long.
* The video shows at least one slide with requirements (done by POs).
* The video shows at least one slide with design/architecture.
* The video shows a demo of the software.
* The video contains spoken audio that explains the software.

## Definition of done (DoD)
* Code compiles and builds 
* Acceptance criteria are met
* Tests have been written and were passed 
* Code is peer-reviewed 
* Feature is merged into development branch
* Documentation is updated 
* Bill of Materials is updated

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by Da-Lang-CS** [comment]
[DemoDayVideoScript.txt](https://github.com/amosproj/amos2022ws02-automotive-test-app/files/10517556/DemoDayVideoScript.txt)

**Comment by BETuncay** [comment]
Also habe damit mal ein demo video gemacht. Ich hab 3 bereiche presentiert aber das ist schon 2:00 Minuten lang.
Ich glaube zeitlich können wir nur 2 bereiche demonstrieren

https://drive.google.com/file/d/1_jRZL65n9OZ78-5EyRaFxjEuN3t8vpUp/view
