### ISSUE TITLE
Implement functionality to switch off the display

### ISSUE THREAD

**Issue by stefanieschreiner** [amosproj/amos2022ws02-automotive-test-app#52]
## User story
1. As a User
2. I want to be able to switch off the display 
3. So that it is off. 

It should be possible to switch off a display immediately, delayed by 30 secs or delayed by 1min.
It should not be possible to trigger a Use Case again if it has already been activated, i.e. if Switch off display was activated after 1min, the use case should not be triggered again within this minute.

## Acceptance criteria
* In the power management area there is a possibility to switch of the display immediately.
* In the power management area there is a possibility to switch off the display after 30 seconds or after one minute.
* It is not possible to trigger a use case again if it has already been activated.

## Definition of done (DoD)
* Code compiles and builds 
* Acceptance criteria are met
* Tests have been written and were passed 
* Code is peer-reviewed 
* Feature is merged into development branch
* Documentation is updated 
* Bill of Materials is updated

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by Andy3189** [comment]
Wartet auf Industriepartner Antwort.

**Comment by stefanieschreiner** [comment]
Not feasible within the scope of this project
