### ISSUE TITLE
Implement functionality to set the system in stand-by mode

### ISSUE THREAD

**Issue by stefanieschreiner** [amosproj/amos2022ws02-automotive-test-app#54]
## User story
1. As a User
2. I want to be able to set the system in stand-by mode
3. So that the display and any audio signal is switched off

It should be possible to set the system in stand-by mode immediately, delayed by 30 secs or delayed by 1min.
It should not be possible to trigger a Use Case again if it has already been activated, i.e. if stand-by mode was activated after 1min, the use case should not be triggered again within this minute.

For CarPlay: Standby mode is composed of " Switch off display" and "Mute system" 

## Acceptance criteria
* In the power management area there is a possibility to set the system in stand-by mode immediately.
• In the power management area there is a possibility to set the system in stand-by mode after 30 seconds or after one minute.

## Definition of done (DoD)
* Code compiles and builds 
* Acceptance criteria are met
* Tests have been written and were passed 
* Code is peer-reviewed 
* Feature is merged into development branch
* Documentation is updated 
* Bill of Materials is updated

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by stefanieschreiner** [comment]
Not feasible in the scope of this project

**Comment by stefanieschreiner** [comment]
Not feasible within the scope of this project

**Comment by i315315** [comment]
Not feasible within the scope of this project
